#' Fetch the sample data from the GFBIOSQL database
#' The data will be filtered to only include hake major and minor areas
#'
#' @param overwrite Logical. Overwrite the RDS file for sample data if it exists
#'
#' @export
#' @importFrom gfdata get_commercial_samples
fetch_sample_data_gfdata <- function(overwrite = FALSE){
  major_areas <- c("02", "03", "04", "05", "06", "07", "08", "09")
  # Include BC offshore and St. of Juan de Fuca (Major 1, Minor 20)
  if(overwrite || !file.exists(here("data", sample_data_raw_file))){
    d <- get_commercial_samples(225) %>%
      filter(major_stat_area_code %in% major_areas |
               (major_stat_area_code == "01" & minor_stat_area_code == "20"))
    saveRDS(d, here("data", sample_data_raw_file))
  }else{
    message("The database query was not run because the file '",
            here("data", sample_data_raw_file), "'
            exists and you didn't set overwrite = TRUE")
  }
}


#' load the commercial sample data from the file generated by [fetch_sample_data_gfdata()]
#'
#' @return
#' @export
load_sample_data <- function(){
  fn <- here("data", sample_data_raw_file)
  if(file.exists(fn)){
    readRDS(fn)
  }else{
    stop("The file '", fn, "' does not exist. Run fetch_sample_data_gfdata() to create.",
         call. = FALSE)
  }
}
